implement thumbs_up and thumbs_down reaction
RazzleAi/razzle-server pull request #41
Opened 2023-07-12 13:56 UTC by Badiru27

2023-07-12 14:10 UTC, flygerian requested changes

2023-07-12 14:10 UTC, flygerian commented on engine/client/client.go
> +
Too much whitespace

2023-07-12 14:10 UTC, flygerian commented on ui/src/pages/chats/ChatHistoryItem.svelte
> +  const handleReaction = (reaction:Reaction) => {
Add some space here. Section is a bit unreadable

2023-07-12 14:10 UTC, flygerian commented on engine/client/client.go
> +	for i := 0; i < historyLength; i++ {
I think this approach might fail in the coming months, but for now it's okay. We would definitely need to refactor it tho.

2023-07-12 14:25 UTC, Badiru27 commented on engine/client/client.go
> +	for i := 0; i < historyLength; i++ {
Yeah, really weird having to loop through since I already have the historyId

2023-07-13 06:50 UTC, flygerian approved these changes

2023-07-13 06:50 UTC, merged